name: Generate Ontology Documentation

on:
    push:
        branches: [main]
        paths:
            - "**.rdf"
            - "**.owl"
            - "sections/**"

    workflow_dispatch:

jobs:
    generate-docs:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Set up Java
              uses: actions/setup-java@v3
              with:
                  distribution: "temurin"
                  java-version: "11"
            - name: Download WIDOCO
              run: |
                  wget https://github.com/dgarijo/Widoco/releases/download/v1.4.25/widoco-1.4.25-jar-with-dependencies_JDK-11.jar
            - name: Generate documentation
              run: |
                  ls -lah; java -jar widoco-1.4.25-jar-with-dependencies_JDK-11.jar \
                  -ontFile beerecipe.rdf \
                  -outFolder docs \
                  -getOntologyMetadata \
                  -rewriteAll \
                  -webVowl \
                  -abstract sections/abstract-en.html \
                  -introduction sections/introduction-en.html \
                  -includeImportedOntologies

            - name: Deploy to GitHub Pages
              uses: peaceiris/actions-gh-pages@v3
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}
                  publish_dir: ./docs


